FROM alpine
#Update and Upgrade apt
RUN apk update

#Install Apache, MySQL and PHP
RUN apk add apache2
RUN apk add curl
RUN apk add php libapache2-mod-php php-mcrypt php-mysql
RUN systemctl restart apache2
RUN apk add php-cli

#Install GIT for website
RUN apk add git
RUN cd /var/www/html/
RUN git clone https://github.com/SamP10/UniVulnerableWebsite.git
RUN systemctl restart apache2
EXPOSE 80 8080