FROM ubuntu
#Update and Upgrade apk
RUN apt-get update && apt-get upgrade -y

#Install Apache, MySQL and PHP
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y apache2
RUN apt-get install -y php libapache2-mod-php php-mysql
RUN apt-get install -y php-cli
RUN apt-get install -y mysql-server

#Install GIT for website
RUN apt-get install -y git
RUN git clone https://github.com/SamP10/UniVulnerableWebsite.git
#RUN mv UniVulnerableWebsite /var/www/localhost/htdocs/
EXPOSE 80 8080